### ISSUE TITLE
Finger tracking for D415

### ISSUE THREAD

**Issue by 666tua** [3DiVi/nuitrack-sdk#11]
Can realsenseD415 use nuitrack to identify 22 joint points on the finger? So as to perform hand tracking. Thanks！

**Comment by VadimAspirin** [comment]
Hi @L-xn,

Do you mean finger tracking? It isn't supported at the moment and it's in our roadmap, but so far without an exact implementation date. But Nuitrack has a Hand Tracker that provides [this](https://download.3divi.com/Nuitrack/doc/structtdv_1_1nuitrack_1_1Hand.html#aced2ba408ee8aabd5b1c157ab766e6e0) information about each user's hands.
