### ISSUE TITLE
RGB Color not detected in Unity

### ISSUE THREAD

**Issue by dldpidodido** [3DiVi/nuitrack-sdk#16]
Hi, 

I would like to raise this current issue in unity that did not recognize the RGB Color, I hope it will fix immediately ;)

Thanks

**Comment by EugeneVasiliev** [comment]
Hello!

What sensor do you use?

Try running the scene (switch the project to the **Standalone** platform): `Assets\NuitrackSDK\Tutorials\GPUVisualization\GPUDrawFrames`

What result did you get? If there is no image, send the output of the Unity console.

**Comment by andrey-tsb** [comment]
Closed due to inactivity.  
Please feel free to reopen or create new issue in case of any questions.
