### ISSUE TITLE
Implementing HandsInput on unity-webview

### ISSUE THREAD

**Issue by eddyaboumansour** [3DiVi/nuitrack-sdk#19]
Hello, first thank you for this tutorial it's very helpful but instead of a gallery I'm using a WebView that displays a webpage (Google Earth globe). I'm being able to move the two hand pointers on the canvas but Mouse, Move, Drag processes are not working on the WebView, what seems to be the problem? Aren't the pointers acting as a mouse already? And aren't the OnClick events of a webpage already implemented ? I would love a small guide on how to achieve this solution. I've added a screenshot of my project's architecture. Thank you! 

![PI - SampleScene - PC, Mac   Linux Standalone - Unity 2020 3 4f1 Personal _DX11_ 4_25_2021 8_49_10 AM (2)](https://user-images.githubusercontent.com/49775809/115983738-576dd480-a5a3-11eb-8726-654dbfa832f5.png)

**Comment by EugeneVasiliev** [comment]
Pointers only interact with the Unity.UI interface system.
Pointers do not replace the behavior of the mouse pointer at the system level.

If you want pointers to work with objects inside a WebView, you first need to learn how WebView handles incoming mouse events.

**Comment by eddyaboumansour** [comment]
@EugeneVasiliev Okay thank you for your help ! I'll check the WebView scripts

**Comment by andrey-tsb** [comment]
Closed due to inactivity, please feel free to reopen or create new in case of any issues.
