### ISSUE TITLE
Uninstalling nuitrack gets stuck on the following "error"

### ISSUE THREAD

**Issue by TandersT** [3DiVi/nuitrack-sdk#22]
During the uninstall, the uninstaller gets stuck on the following message:

C:\WINDOWS\system32>reg add "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" /v Path /t REG_EXPAND_SZ /d "%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Program Files\OpenNI\Bin64;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\ZeroTier\One\" /f 
Value Path exists, overwrite(Yes/No)? 

**Version: 0.29.0
Platform: Windows 10**

**Comment by VadimAspirin** [comment]
Hi @TandersT,

It looks like an uninstaller bug in the old Nuitrack version. You can uninstall Nuitrack manually as follows:
- remove the path to Nuitrack from the PATH environment variable 
- remove the Nuitrack directory (located in the %NUITRACK_HOME% directory)
- remove the NUITRACK_HOME environment variable

**Comment by andrey-tsb** [comment]
Closed due to inactivity.  
Please feel free to create new issue in case of any questions.

**Comment by 941631877** [comment]
ERROR: Sample failed. Exit code: 3
