### ISSUE TITLE
This repository is over its data quota

### ISSUE THREAD

**Issue by arashAk** [3DiVi/nuitrack-sdk#25]
I received an error while trying to pull the platforms and unity custom package. does anyone face the same problem?

$ git lfs pull --include "Platforms/*"
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/3DiVi/nuitrack-sdk.git/info/lfs'

**Comment by VadimAspirin** [comment]
Hi @arashAk,

We fixed this issue on our side, please try again.

**Comment by arashAk** [comment]
Perfect Thanks,
