### ISSUE TITLE
Failed to import package with error: Couldn't decompress package

### ISSUE THREAD

**Issue by lanlan3322** [3DiVi/nuitrack-sdk#26]
Unity3D package for 0.35.9
Error while importing into Unity 2020.3.18f1:
Failed to import package with error: Couldn't decompress the package

**Comment by reuksv** [comment]
Hello @lanlan3322 
If you try to unpack another package into your project, will there be the same error?

**Comment by lanlan3322** [comment]
Thanks,
It works now.
I think the file was corrupted yesterday.
