### ISSUE TITLE
Nuitrack_ARM64.apk v0.35.9 and UI problem not allowing license input

### ISSUE THREAD

**Issue by sbattaglino** [3DiVi/nuitrack-sdk#27]
After App installation, I can see the loading bar with progress. But the Nuitrack Logo stretches together with the loading bar, displacing all other components. I miss the input for license and the selection

https://user-images.githubusercontent.com/51378778/136256425-bb1194a9-7063-4f1c-877d-6b08de765872.mov

 for devices.
This is happening with v0.35.8 as well. I had to roll back to v0.35.7

**Comment by VadimAspirin** [comment]
Hi @sbattaglino, please try to use Nuitrack v0.35.11, is it correctly on this version?

**Comment by sbattaglino** [comment]
Hi @VadimAspirin. We're currently using v0.35.10 and the issue is fixed. We're planning to upgrade to Nuitrack v0.35.11 in the next weeks. Thanks!
