### ISSUE TITLE
Getting java.io.FileNotFoundException OpenNI.ini in a device without sdcard on Android API 30

### ISSUE THREAD

**Issue by sbattaglino** [3DiVi/nuitrack-sdk#28]
Nuitrack Pro, RealSense 435. Android ARM64 v0.35.10.

The path `/storage/emulated/0/Android/data/com.tdv.nuitrack.sdk/files/nuitrack/` does not exists on my device.
The files of the SDK are here: `/data/media/0/Android/data/com.tdv.nuitrack.sdk/files/nuitrack/`

W/System.err: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.tdv.nuitrack.sdk/files/nuitrack/OpenNI.ini: open failed: EACCES (Permission denied)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:492)
W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:160)
W/System.err:     at com.tdv.nuitrack.sdk.OpenNI2Config.copyIniToAppFolder(OpenNI2Config.java:22)
W/System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err:     at libcore.io.Linux.open(Native Method)
W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err:     at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7546)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:478).

CmakeList.txt file:
`
# https://developer.android.com/studio/projects/configure-cmake
cmake_minimum_required(VERSION 3.4.1)

add_library(nuitrack_gl_sample SHARED
        ${CMAKE_CURRENT_SOURCE_DIR}/android_main.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/NuitrackGLSample.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/dummy-lib.cpp)

set(NUITRACK_SDK_PATH ${CMAKE_CURRENT_SOURCE_DIR})

set(ANDROID_ARCH android)
if(ANDROID_ABI STREQUAL "arm64-v8a")
    set(ANDROID_ARCH android-arm64)
endif()

add_library(app-glue STATIC ${ANDROID_NDK}/sources/android/native_app_glue/android_native_app_glue.c)
include_directories(${NUITRACK_SDK_PATH}/Nuitrack/include ${ANDROID_NDK}/sources/android/native_app_glue)

add_library(nuitrack SHARED IMPORTED)
set_target_properties(nuitrack PROPERTIES IMPORTED_LOCATION ${NUITRACK_SDK_PATH}/Nuitrack/lib/${ANDROID_ARCH}/libnuitrack.so)

add_library(middleware SHARED IMPORTED)
set_target_properties(middleware PROPERTIES IMPORTED_LOCATION ${NUITRACK_SDK_PATH}/Nuitrack/lib/${ANDROID_ARCH}/libmiddleware.so)

add_library(openni SHARED IMPORTED)
set_target_properties(openni PROPERTIES IMPORTED_LOCATION ${NUITRACK_SDK_PATH}/Nuitrack/lib/${ANDROID_ARCH}/libOpenNI.so)

find_library(log-lib log)
find_library(android-lib android)
find_library(egl-lib EGL)
find_library(gles-lib GLESv1_CM)

target_link_libraries(nuitrack_gl_sample app-glue ${log-lib} ${android-lib} ${egl-lib} ${gles-lib} nuitrack middleware)
`

**Comment by VadimAspirin** [comment]
Hi @sbattaglino, do you have the same error message when running a demo in a Nuitrack app?

**Comment by sbattaglino** [comment]
Hi @VadimAspirin. Yes, I have the same error on the Demo. It looks like is just a Warning. Because Nuitrack is working as expected. I'm not sure what's the purpose of that file OpenNI.ini

**Comment by VadimAspirin** [comment]
Hi @sbattaglino, Has your issue been solved? The OpenNI.ini file is a configuration file and don't worry, Nuitrack doesn't use this file for Realsense sensors working in Nuitrack.

**Comment by VadimAspirin** [comment]
I'm closing this issue, if you have other questions, you can open it again.
