### ISSUE TITLE
$NUITRACK_HOME/qt/lib/fonts missing in latest nuitrack-ubuntu-amd64.deb

### ISSUE THREAD

**Issue by jimruxton** [3DiVi/nuitrack-sdk#29]
The nuitrack shell script sets QT_QPA_FONTDIR=$NUITRACK_HOME/qt/lib/fonts/  however the fonts directory is missing in the latest nuitrack-ubuntu-amd64.deb package. Not sure if this is relevant to issue #24.

**Comment by VadimAspirin** [comment]
Hi @jimruxton, QT application is using system fonts in this situation, I think your previous issue has another reason.

**Comment by VadimAspirin** [comment]
Hi @jimruxton,

Has this issue been solved? Can i close it?
