### ISSUE TITLE
Unity keeps warning you to update tbb.dll even if it has already been replaced.

### ISSUE THREAD

**Issue by BasPaap** [3DiVi/nuitrack-sdk#32]
In the troubleshooting document, the following is mentioned regarding tbb.dll:

>Replace the TBB library in your Unity editor with the library from Nuitrack:
Windows: copy the tbb.dll library from %NUITRACK_HOME%/bin to your Unity editor folder (for example, C:\Program Files\Unity\Hub\Editor\2019.4.8f1\Editor)

This is not enough. You will keep getting a warning that you need to replace tbb.dll when opening the project in Unity. If you accept and restart, the message will pop up again. You need to manually add a file called "tbb_backup.dll" to the same folder for the messages to cease.

This happens on version 0.35.12 with the corresponding Unity package, in unity 2020.3.12f1.

**Comment by reuksv** [comment]
https://github.com/3DiVi/nuitrack-sdk/issues/31#issuecomment-994469715
