### ISSUE TITLE
Uninstallation stuck at 33%

### ISSUE THREAD

**Issue by wldevries** [3DiVi/nuitrack-sdk#34]
I want to uninstall Nuitrack 0.35.9 in order to update to a newer version, but the uninstaller gets stuck at 33%. The detail window remains completely empty. How do I get rid of it? I could remove the directory and the environment variables, but I want to get rid of it from my Apps & Features as well.

**Comment by ir4kli09** [comment]
Hi @wldevries,

Please, try the following instructions:

1. Run `сlear_sys_env.bat` from Nuitrack runtime as Administrator (search in C:\Program Files\Nuitrack\ for x64);
2. Run maintenancetool.exe;
3. Install Nuitrack once again.

**Comment by wldevries** [comment]
Thanks, that worked.
