### ISSUE TITLE
LibYAML Conflict

### ISSUE THREAD

**Issue by atyshka** [3DiVi/nuitrack-sdk#35]
On Ubuntu 18.04, Nuitrack seems to coexist fine with other applications, but on Ubuntu 20.04 I am noticing undefined symbols due to Nuitrack's version of libyaml-cpp overriding the system default at `/lib/x86_64-linux-gnu/libyaml-cpp.so.0.6`. Is there a reason nuitrack must ship its own version rather than using the system default? Any workarounds to get other applications working again?

**Comment by ir4kli09** [comment]
Hi @atyshka,

Try using this command `LD_LIBRARY_PATH=   <your_app>`  when running other programs.

**Comment by atyshka** [comment]
I tried that earlier but now it seems to work. Thanks!
