### ISSUE TITLE
Nuitrack activation tool does not support desktop scaling

### ISSUE THREAD

**Issue by wldevries** [3DiVi/nuitrack-sdk#37]
My desktop is set to 150% scaling. Some text scales up, but the layout is not adjusted.
![image](https://user-images.githubusercontent.com/1745610/155705899-51405631-0f5b-4629-9313-8ddcfb8f4429.png)

**Comment by wldevries** [comment]
This is on Windows 10 64 bit 21H1

**Comment by logisticAKB** [comment]
Hi @wldevries 

Try to create new user environment variable QT_SCALE_FACTOR and set value 1.5 for it

**Comment by logisticAKB** [comment]
Hi @wldevries 

Has your issue been solved? Do you have any other questions that I can help you with?
