### ISSUE TITLE
Nuitrack Linux error - Please run as current user 

### ISSUE THREAD

**Issue by tomassilny** [3DiVi/nuitrack-sdk#39]
Hi,
I am getting this error message when I type `nuitrack` after installing the latest Nuitrack SDK on Orange Pi:

![image](https://user-images.githubusercontent.com/24394509/167305752-a1af64b7-6eff-45ba-b9c6-37444af7513f.png)

I tried also `sudo nuitrack` with the same result.

My specifications:
HW: OrangePi 3 LTS
OS: Debian buster 2.1.6
ARCH: arm64
NUITRACK SDK VERSION: [v0.35.14](https://github.com/3DiVi/nuitrack-sdk/commit/e0a0005d83827c12215f505eb764249ac4173a15)

Thank you for any tips!

**Comment by logisticAKB** [comment]
Hi @tomassilny 

You should run Nuitrack as a non-root user

**Comment by logisticAKB** [comment]
Hi @tomassilny 

Has your issue been solved? Do you have any other questions I can help you with?

**Comment by logisticAKB** [comment]
Hi @tomassilny 

How do you use your OrangePi? Are you connected via SSH or directly with monitor connected to OrangePi?

**Comment by tomassilny** [comment]
@logisticAKB I am connected via SSH

**Comment by tomassilny** [comment]
Okay, that was a problem, I installed VNC viewer and now it works! Thank you
