### ISSUE TITLE
support on orbbec astra+

### ISSUE THREAD

**Issue by lzcchl** [3DiVi/nuitrack-sdk#40]
hello, I can't run any exe successed in "nuitrack\bin" when I use orbbec astra+ just like the white one in web https://developer.orbbec.com.cn/module.html.

and I check orbbec SDK at https://developer.orbbec.com.cn/download.html?id=77, the official "OpenNI_SDK" is not support astra+, only "orbbec_SDK" support astra+.

and I see there are "orbbec.dll"/"OniFile.dll" in floder "nuitrack\bin\OpenNI2\Drivers", these dll is in orbbec OpenNI_2.3.0.81.zip which is download from orbbec web. and I use "OpenNI_2.3.0.81\Win64-Release\tools\NiViewer\NiViewer.exe" can't open camera either.

so I'm doubt that nuitrack is really support astra+, is that only support astra pro?@https://nuitrack.com/#sensors

i push my error, there is "AstraProPerseeDepthProvider: Can't open device (" in image, but no info about astra+ or astraplus

![image](https://user-images.githubusercontent.com/34515022/167603301-573d3bb9-9d0c-40dc-9c84-7b09d0297d02.png)

**Comment by VadimAspirin** [comment]
Hi @lzcchl,

We apologize for the inconvenience, this is a known issue with the new revision of Astra+ and we are preparing a fix for it in the new release (approximately today or tomorrow).

**Comment by VadimAspirin** [comment]
Hi @lzcchl,

We fixed this in [v0.35.15](https://github.com/3DiVi/nuitrack-sdk/releases/tag/v0.35.15). Try using the latest version to make sure the issue is resolved.

**Comment by lzcchl** [comment]
yes, it works well, good job!
