### ISSUE TITLE
Azure Kinect DK nuitrack.config isn't applying

### ISSUE THREAD

**Issue by KlavsKalnins** [3DiVi/nuitrack-sdk#44]
Model: Azure Kinect DK (AzureKinectDepthProvider)
Tested the config in nuitrack application and Unity Render Texture

In unity my kinect isn't changing the RGB width and height it stays natively 640x480
<img width="335" alt="Code_MakYmrv4ls" src="https://user-images.githubusercontent.com/44971504/180227340-631d7500-0ac5-4697-83b5-1b16fa681970.png">

Everything works for my "Intel RealSense D455(Realsense2DepthProvider)"
<img width="282" alt="Code_pNO6p831Oe" src="https://user-images.githubusercontent.com/44971504/180227502-3c269746-1785-45ac-aa51-795926d2b993.png">

note: I even tried different names like "AzureKinectDepthProvider", "AzureKinectDKDepthProvider"

Firmware and unity sdk is the latest

**Comment by ir4kli09** [comment]
Hi @KlavsKalnins,
You can find the answer to your question here [community.nuitrack.com](https://community.nuitrack.com/t/azurekinect-dk-nuitrack-config-isnt-applying/3049/2?u=irakli)
