### ISSUE TITLE
joint parameter orientation

### ISSUE THREAD

**Issue by TunahanApaydin** [3DiVi/nuitrack-sdk#48]
Hi,
What is the orientation parameter mean in skeleton? It returns 3x3 matrix. Is there any relationship between real or projection values and orientation matrix? What and how can I use the orientation matrix?
Thank you.

Note: I'm using Python API.

**Comment by logisticAKB** [comment]
Hi @TunahanApaydin 

This parameter stores the spatial orientation as a 3x3 rotation matrix. 

Please refer to the following materials: 
- https://community.nuitrack.com/t/joint-orientation-rule/1468 
- https://community.nuitrack.com/t/local-joint-coordinate-rotation-matrix-problem/582
​

They can be considered as official answers (were provided by Nuitrack team)

**Comment by logisticAKB** [comment]
Hi @TunahanApaydin 

Do you have any other questions I can help you with?

**Comment by TunahanApaydin** [comment]
Thanks for helping. I have solved my problem.
