### ISSUE TITLE
nuitrack-linux-armhf.deb compiled on 64-bit linux?

### ISSUE THREAD

**Issue by wolfysong** [3DiVi/nuitrack-sdk#49]
Hi, all, tried to import PyNuitrack on a Raspberry PI 4 and get the following error.

from PyNuitrack import py_nuitrack
ImportError: /usr/local/lib/python3.7/dist-packages/PyNuitrack/py_nuitrack.so: wrong ELF class: ELFCLASS64

is the nuitrack-linux-armhf.deb compiled on 64-bit linux? anyone can help. Thanks

**Comment by logisticAKB** [comment]
Hi @wolfysong 

For the linux arm64 you'll need to install [nuitrack-linux-arm64.deb](https://github.com/3DiVi/nuitrack-sdk/blob/master/Platforms/nuitrack-linux-arm64.deb)

**Comment by logisticAKB** [comment]
Hi @wolfysong 

Has your issue been solved? Do you have any other questions I can help you with?
