### ISSUE TITLE
Unity package can not be imported

### ISSUE THREAD

**Issue by shahanpower** [3DiVi/nuitrack-sdk#5]
I have tried importing the unity package but always get this error message. I have tried on different versions of Unity but i get the same issue.
Current Unity version 2019.4.14

**Failed to import package with error: Couldn't decompress package**

**Comment by takesi0627** [comment]
@shahanpower 
Did you do this before import the package? (Reference from Readme.md)

```
$ git lfs pull --include "Unity3D/*"
```

I get the same message and this worked for me.
