### ISSUE TITLE
How to use the CPU MaxLoad value in the Nuitrack.config file?

### ISSUE THREAD

**Issue by emanuelgollob** [3DiVi/nuitrack-sdk#51]
### Discussed in https://github.com/3DiVi/nuitrack-sdk/discussions/50

<div type='discussions-op-text'>

<sup>Originally posted by **emanuelgollob** September 24, 2022</sup>
Hello everyone,
I use the Nuitrack C# sample with the AI skeleton tracker and would like to limit the maximum CPU usage.
I found this setting in the nuitrack.config but couldn´t find any explanation for it:
  
    "CPU": {
        "MaxLoad": -1.0
    },

I guess -1.0 means no restriction at all, but how could I set it to, e.g. 60% of my maximum CPU power?

Thank you!</div>

**Comment by logisticAKB** [comment]
Hi @emanuelgollob 

Answered to you on [community](https://community.nuitrack.com/t/how-to-use-the-cpu-maxload-value-in-the-nuitrack-config-file/3110/2?u=a.bragin)
