### ISSUE TITLE
NUITrack not starting on Windows 11

### ISSUE THREAD

**Issue by missbella90** [3DiVi/nuitrack-sdk#56]
Hey there,
Nuitrack wont start on my system
Running Windows 11
Error message is:
The ordinal 901 could not be located in the dynamic link library (path to inferrence_engine.dll)
Second Error message is:
The ordinal 900 could not be located in the dynamic link library (path to inferrence_engine_legacy.dll)

cant get any more outputs there

**Comment by logisticAKB** [comment]
Hi @missbella90 

You need to install Visual C++ Redistributable specified in the installation documentation (https://github.com/3DiVi/nuitrack-sdk/blob/master/doc/Install.md#windows)

**Comment by missbella90** [comment]
Strange thing is that it tells me that it's already installed..
i guess it has been installed from visual studio or such..

**Comment by missbella90** [comment]
Also got all the Visual C++ installed from 2005-2022
the version 2015-2019 wont install unless i delete the 2015-2022 which i need for VS community 2022

**Comment by logisticAKB** [comment]
Could you tell us what exact set of c++ redistributables is installed on your system?

For example with this set of c++ redistributables Nuitrack works on Windows 11 just fine
![image](https://user-images.githubusercontent.com/42612598/224266689-5f9b3157-b7f0-4529-82a9-07c5ecc10184.png)

**Comment by missbella90** [comment]
Got the same except back to 2005
and i got the c++ 2015-2022 Redis (x64)

**Comment by logisticAKB** [comment]
Hi @missbella90, any updates on the issue?
