### ISSUE TITLE
Python wheel for Ubuntu 22.04

### ISSUE THREAD

**Issue by fdila** [3DiVi/nuitrack-sdk#57]
Could you make the python wheel compatible with Ubuntu 22.04?

**Comment by logisticAKB** [comment]
Hi @fdila,

Based on our testing, python wheel is compatible with Ubuntu 22.04. Have you encountered any specific issue?

**Comment by fdila** [comment]
That's pretty weird. I was trying to install it a couple weeks ago and pip threw an error, saying that the wheel was not compatible.
I reinstalled Ubuntu 22.04 for unrelated reasons and tried again and now everything works. 

Thanks.
