### ISSUE TITLE
cannot select my kinect v1

### ISSUE THREAD

**Issue by jingerbreadBiliBili** [3DiVi/nuitrack-sdk#58]
I got a kinect v1 and i try to use a another program to do 3D dynamic capture to a model ,it use nuitrack but it cannot discover my kinect

**Comment by jingerbreadBiliBili** [comment]
there is a normal sdk (v1.6) on my computer
i don't know will is that reason

**Comment by jingerbreadBiliBili** [comment]
whatever

**Comment by logisticAKB** [comment]
Hi @jingerbreadBiliBili 

Could you describe the problem in details?

- Is your kinect v1 detected by latest Nuitrack.exe?
- What software do you use that cannot detect your sensor? How is it related to Nuitrack?
- What do you mean by  "normal sdk (v1.6)"?

**Comment by logisticAKB** [comment]
Hi @jingerbreadBiliBili 

We are interested in understanding the problem and helping you solve it. 
Could you clarify to us the details requested above?
