### ISSUE TITLE
PyNutrack used on Persee Plus

### ISSUE THREAD

**Issue by longgood** [3DiVi/nuitrack-sdk#64]
OS:Ubuntu 18.04.6 LTS
Python:3.6.9
whl version: py-nuitrack-ubuntu 0.0.1

error comes from the first line
**from PyNuitrack import py_nuitrack**

it shows 
/home/path/env_nuitrack/lib/python3.6/site-packages/PyNuitrack/**py_nuitrack.so**: cannot open shared object file: No such file or directory,

I just checked that file exist, at the size of 2784984.

thanks for working on this

**Comment by ir4kli09** [comment]
We released [PyNuitrack](https://github.com/3DiVi/nuitrack-sdk/blob/master/PythonNuitrack-beta/pip_packages/dist/linux/py_nuitrack_ubuntu_arm64-0.1.0-py3-none-any.whl) for linux arm64 on February 16th
