### ISSUE TITLE
Maximum detection range

### ISSUE THREAD

**Issue by machongrun** [3DiVi/nuitrack-sdk#66]
Your tools are amazing! I want to know what the maximum detection range of the Skeleton tracking SDK is ？
Many thanks！

**Comment by andrey-tsb** [comment]
Hi @machongrun, sorry for late reply.
Actually it depends on a specific sensor resolution and field of view (primarily horizontal).
What should be expected on average - 3-4 meters. For some sensors - up to 5-6 meters. 
For proper sensors it could be additionally fine-tuned (with increased CPU/GPU usage) - possibly up to 7-8 meters.
In general, higher working distances aren't feasible on depth sensors.

**Comment by andrey-tsb** [comment]
Hi @machongrun , how are you? 
What depth sensor do you currently?
With this information we'll be able to provide a more accurate answer and could assist with Nuitrack fine-tuning.
