### ISSUE TITLE
UE5 plugin error 

### ISSUE THREAD

**Issue by ancillarymagnet** [3DiVi/nuitrack-sdk#71]
Trying to run the marketplace version of the plugin on UE 5.2 results in an error ...

![image](https://github.com/3DiVi/nuitrack-sdk/assets/9907697/9dd54bbf-00ca-4937-8624-79481ababc16)

This happens when trying to play in editor on any of the levels in the plugin Samples directory, using an Orbbec Femto Bolt on Nuitrack SDK 0.37.13.

**Comment by pc2555** [comment]
Me too

**Comment by reuksv** [comment]
Hello @ancillarymagnet @pc2555 
We are already working on a solution to this problem. Try using the previous version of Nuitrack (0.37.12)
https://github.com/3DiVi/nuitrack-sdk/blob/v0.37.12/Platforms/nuitrack-windows-x64.exe

**Comment by ancillarymagnet** [comment]
I was able to get these examples to work with 0.37.12 thanks

**Comment by reuksv** [comment]
@ancillarymagnet @pc2555 
Plugin Updated :rocket: (fixed compatibility with the latest version of Nuitrack)
https://www.unrealengine.com/marketplace/en-US/product/nuitrack-real-time-body-tracking
