### ISSUE TITLE
TouchDesigner integration not finding device

### ISSUE THREAD

**Issue by ancillarymagnet** [3DiVi/nuitrack-sdk#72]
Using Nuitrack 0.37.13 and TouchDesigner 2023.11510 or 11290 with an Orbbec Femto Bolt, whether:

* Creating a new .toe file and dropping a new Nuitrack CHOP 
or
* opening the provided Nuitrack-Sample.toe

and whether running the Nuitrack demo (Try Nuitrack! button in the Nuitrack app) or not,

... the CHOP shows an error in TouchDesigner:
![image](https://github.com/3DiVi/nuitrack-sdk/assets/9907697/3990d404-de74-4cc4-bb6f-14494a1f4b68)

**Comment by ir4kli09** [comment]
Hello @ancillarymagnet 
Thank you for bringing this issue to our attention. We will test the plugin with version TD 2023 and get back to you with an update as soon as possible.

**Comment by ir4kli09** [comment]
Hello @ancillarymagnet 
I tested the plugin on version TD 2023.11220, it works as expected. But I was able to reproduce your problem. Could you tell me if you had another app running in the background using your sensor? If yes, please close it and run the TD sample again.

**Comment by ancillarymagnet** [comment]
Hi @ir4kli09 just to confirm I did a test from a reboot, straight into 2023.11290, no other applications running, and still have the issue.

**Comment by ir4kli09** [comment]
Hello @ancillarymagnet 
We have solved the problem, we will release an update soon

**Comment by andrey-tsb** [comment]
Hi @ancillarymagnet, you are welcome to try the latest release ([0.37.15](https://github.com/3DiVi/nuitrack-sdk/releases/tag/v0.37.15)) for the relevant TouchDesigner compatibility fix.

**Comment by ancillarymagnet** [comment]
Hi @andrey-tsb - I installed 0.37.15 and re-downloaded the Nuitrack-sample.toe (in case it was updated? hard to tell at the bit.ly link) and tried TouchDesigner 2023.11290 and 11510 ... still have the same problem as before: "Error: Check if the device is connected and reload the plugin."
