### ISSUE TITLE
Kinect support

### ISSUE THREAD

**Issue by COcisuts** [3DiVi/nuitrack-sdk#76]
Greetings, im trying to connect a kinect v1 or a kinect v2 or a kinect azure in unreal engine, but only v1 and v2 are recognized as nui camera by usbdeview, and the azure isn't recognized at all. The camera of the v1 is connecting and disconnecting continuosly... The v2 beside the nui camera and the mic as in v1 has a wdf kinectSensor Interface 0 too enumerated on usbdeview/device list, it isn't disconnecting, but the license activator doesn't find anything with all 3 sensors... Should i install also the windows kinect sdk or runtime besides openni for all sensors or just azure one? Back in the day the coexistence was giving problems... The path is fine, but what exactly needs admin permissions?

**Comment by COcisuts** [comment]
I managed to make it start on the v1 un/reinstalling everything... It s recognized as a Kinect(OpenNI2DepthProvider)(00000000000) but when i insert the licence it gives me an Activation error:Server error response: License signature is incorrect. Wrong serial. 
Maybe because is an xbox kinect?

**Comment by ir4kli09** [comment]
Hello @COcisuts 

Sorry for a delayed reply.
Please check this https://community.nuitrack.com/t/account-activation-error-in-the-windows-nuitrack-application/3359/2?u=irakli

> Your Kinect sensor has zero serial number (see [000000000000000] shown on your screenshot). That’s unfortunate problem with some old Kinect V1 sensors.
> 
> Nuitrack does not support such sensors.
